name: create release binary
on:
  release:
jobs:
  artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch:
          - amd64
          - s390x
    steps:
      - uses: actions/checkout@v2
      - name: compile and release
        uses: wangyoucao577/go-release-action@v1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: ${{ matrix.goarch }}
          goos: linux
          ldflags: >
            -extldflags -static
            -X "main.Version=${{ github.ref }}"
            -w
            -s
