name: create release binary
on:
  release:
    types: [created]
jobs:
  artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch:
          - amd64
          - s390x
          - arm
          - arm64
          - ppc64le
    steps:
      - uses: actions/checkout@v2
      - name: compile and release
        uses: wangyoucao577/go-release-action@v1.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: ${{ matrix.goarch }}
          goos: linux
          goversion: https://golang.org/dl/go1.15.6.linux-amd64.tar.gz
          ldflags: >
            -extldflags -static
            -X "main.Version=${{ github.ref }}"
            -w
            -s
